language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

before_deploy: npm run build && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_ACCESS_TOKEN
  on:
    branch: master